version: '2'
services:
  syslog:
    image: bobrik/syslog-ng
    restart: always
    volumes:
     - /data/syslog:/var/log/syslog-ng
    ports:
     - 10.10.10.10:514:514/udp
     - 10.10.10.10:514:514/tcp
  radius:
    build: radius
    restart: always
    volumes:
     - /data/radius/etc:/etc/freeradius:ro
     - /data/radius/python:/data/radius-python:ro
    environment:
     - PYTHONPATH=/data/radius-python
    ports:
     - 10.10.10.10:1812:1812/udp
     - 10.10.10.10:1813:1813/udp
     - 10.10.10.10:1814:1814/udp
     - 10.10.10.10:18120:18120/udp
    links:
     - mysql:mysql
  tftpboot:
    build: tftpboot
    restart: always
    ports:
     - 10.10.1.10:69:69/udp
    volumes:
     - /data/tftpboot:/var/lib/tftpboot:ro
  mysql:
    image: mysql:5.5
    restart: always
    volumes:
     - /data/mysql/db:/var/lib/mysql
  web:
    build: nginx
    restart: always
    ports:
     - 10.10.10.10:80:80/tcp
     - 10.10.10.10:443:443/tcp
     - ${PUBLIC_IP}:80:80/tcp
     - ${PUBLIC_IP}:443:443/tcp
    volumes:
     - /data/nginx/ssl:/data/ssl:ro
     - /data/nginx/sites:/etc/nginx/conf.d:ro
     - /data/nginx/logs:/var/log:rw
     - /data/web:/data/sites
     - /data/munin/www/:/data/munin:ro
    links:
     - mysql:mysql
     - jenkins:jenkins
     - unifi:unifi
  mail:
    image: lits/docker-mail-relay
    restart: always
    ports:
     - 10.10.10.10:25:25/tcp
    volumes:
     - /data/mail/spool:/var/spool/mail
     - /data/mail/logs:/var/log
    environment:
     - RELAY_HOST_NAME=stella.event.formulastudent.de
     - ACCEPTED_NETWORKS=10.10.0.0/16 172.16.0.0/12
     - EXT_RELAY_HOST=${SMTP_HOST}
     - EXT_RELAY_PORT=25
     - SMTP_LOGIN=${SMTP_LOGIN}
     - SMTP_PASSWORD=${SMTP_PASSWORD}
     - USE_TLS=yes
     - SMTPD_USE_TLS=yes
     - SMTPD_LOG_LVL=0
  jenkins:
    image: jenkins
    restart: always
    volumes:
     - /data/jenkins:/var/jenkins_home
  unifi:
    build: unifi
    restart: always
    volumes:
     - /data/unifi:/usr/lib/unifi/data
    networks:
      manage:
        ipv4_address: 10.10.3.11
      default:
  munin:
    build: munin
    restart: always
    volumes:
     - /data/munin/logs:/var/log/munin
     - /data/munin/db:/var/lib/munin
     - /data/munin/pid:/var/run/munin
     - /data/munin/www:/var/www/munin
     - /data/munin/etc:/etc/munin

networks:
  default:
    driver: bridge
  manage:
    external: true
