version: '2'
services:
  admin:
    build: admin
    restart: always
    ports:
     - 10.10.1.10:1221:22/tcp
    links:
     - dns:dns
     - mysql:mysql
     - web:web
     - radius:radius
     - tftpboot:tftpboot
    volumes:
     - /root:/root
     - /etc/ssh/sshd_config:/etc/ssh/sshd_config:ro
     - /data:/data
  dns:
    build: bind
    restart: always
    dns: 127.0.0.1
    ports:
     - 10.10.10.10:53:53/udp
     - 10.10.10.10:53:53/tcp
    volumes:
      - /data/bind/var:/var/lib/bind
      - /data/bind/etc:/etc/bind:ro
  radius:
    build: radius
    restart: always
    volumes:
     - /data/radius/etc:/etc/freeradius:ro
     - /data/radius/python:/data/radius-python:ro
    environment:
     - PYTHONPATH=/data/radius-python
    ports:
     - 10.10.10.10:1812:1812/udp
     - 10.10.10.10:1813:1813/udp
     - 10.10.10.10:1814:1814/udp
     - 10.10.10.10:18120:18120/udp
    links:
     - mysql:mysql
  dhcp:
    image: networkboot/dhcpd
    restart: always
    volumes:
     - /data/dhcp:/data
    network_mode: "host"
  tftpboot:
    build: tftpboot
    restart: always
    ports:
     - 10.10.1.10:69:69/udp
    volumes:
     - /data/tftpboot:/var/lib/tftpboot:ro
  mysql:
    image: mysql:5.5
    restart: always
    volumes:
     - /data/mysql/db:/var/lib/mysql
  web:
    build: nginx
    restart: always
    ports:
     - 10.10.10.10:80:80/tcp
     - 10.10.10.10:443:443/tcp
     - ${PUBLIC_IP}:80:80/tcp
     - ${PUBLIC_IP}:443:443/tcp
    volumes:
     - /data/nginx/ssl:/data/ssl:ro
     - /data/nginx/sites:/etc/nginx/conf.d:ro
     - /data/nginx/logs:/var/log:rw
     - /data/web:/data/sites
    links:
     - mysql:mysql
     - jenkins:jenkins
  mail:
    image: lits/docker-mail-relay
    restart: always
    ports:
     - 10.10.10.10:25:25/tcp
    volumes:
     - /data/mail/spool:/var/spool/mail
     - /data/mail/logs:/var/log
    environment:
     - RELAY_HOST_NAME=stella.event.formulastudent.de
     - ACCEPTED_NETWORKS=10.10.0.0/16
     - EXT_RELAY_HOST=${SMTP_HOST}
     - EXT_RELAY_PORT=25
     - SMTP_LOGIN=${SMTP_LOGIN}
     - SMTP_PASSWORD=${SMTP_PASSWORD}
     - USE_TLS=yes
     - SMTPD_USE_TLS=yes
     - SMTPD_LOG_LVL=0
  jenkins:
    image: jenkins
    restart: always
    volumes:
     - /data/jenkins:/var/jenkins_home
  cups:
    build: cups
    restart: always
    ports:
     - 10.10.10.10:631:631/tcp
    volumes:
     - /data/cups/config:/var/cups_config
     - /data/cups/driver:/var/cups_driver
    environment:
     - CUPS_ADMIN=${CUPS_USER}
     - CUPS_PASSWD=${CUPS_PASSWORD}
