version: '2'
services:
  unifi:
    build: unifi
    restart: always
    volumes:
     - /data/unifi:/usr/lib/unifi/data
    networks:
      manage:
        ipv4_address: 10.10.10.11

networks:
  manage:
    external: true
