version: '2'
services:
  unifi:
    build: unifi
    restart: always
    volumes:
     - /data/unifi:/usr/lib/unifi/data
    network_mode: "host"
    ports:
     - 8443:8443/tcp
     - 8880:8880/tcp
     - 8843:8843/tcp
     - 8080:8080/tcp
