version: '2'
services:
  cups:
    build: cups
    restart: always
    ports:
     - 10.10.10.10:631:631/tcp
    volumes:
     - /data/cups/config:/var/cups_config
     - /data/cups/driver:/var/cups_driver
    environment:
     - CUPS_ADMIN=${CUPS_USER}
     - CUPS_PASSWD=${CUPS_PASSWORD}
  asterisk:
    build: asterisk
    restart: always
    volumes:
     - /data/asterisk:/etc/asterisk:ro
    networks:
      manage:
        ipv4_address: 10.10.3.13
  mumble:
    build: murmur
    restart: always
    volumes:
     - /data/murmur:/data
    ports:
     - 10.10.10.10:64738:64738/tcp
     - 10.10.10.10:64738:64738/udp
     - ${PUBLIC_IP}:64738:64738/tcp
     - ${PUBLIC_IP}:64738:64738/udp

networks:
  manage:
    external: true
