version: '2'
services:
  cups:
    build: cups
    restart: always
    ports:
     - 10.10.10.10:631:631/tcp
    volumes:
     - /data/cups/config:/var/cups_config
     - /data/cups/driver:/var/cups_driver
    environment:
     - CUPS_ADMIN=${CUPS_USER}
     - CUPS_PASSWD=${CUPS_PASSWORD}
  asterisk:
    build: asterisk
    restart: always
    volumes:
     - /data/asterisk:/etc/asterisk:ro
    networks:
      manage:
        ipv4_address: 10.10.3.13
  mumble:
    build: murmur
    restart: always
    volumes:
     - /data/murmur:/data
     - /etc/letsencrypt:/data/ssl:ro
     - /data/nginx/sites-mumble:/etc/nginx/sites-enabled:ro
     - /data/web/mumble-web/dist:/var/www:ro
    ports:
     - 10.100.1.10:64738:64738/tcp
     - 10.100.1.10:64738:64738/udp
    networks:
      manage:
        ipv4_address: 10.10.3.16
      dmz:
        ipv6_address: 2001:470:7090:ff64:1::16
  prosody:
    build: prosody
    restart: always
    volumes:
     - /data/prosody/etc:/etc/prosody:ro
     - /data/prosody/logs:/var/log/prosody:rw
     - /data/prosody/modules:/usr/lib/prosody-modules:ro
    ports:
     - ${PUBLIC_IP}:5222:5222/tcp
     - ${PUBLIC_IP}:5280:5280/tcp
     - ${PUBLIC_IP}:5281:5281/tcp
     - ${PUBLIC_IP}:5269:5269/tcp
     - 10.10.10.10:5222:5222/tcp
     - 10.10.10.10:5280:5280/tcp
     - 10.10.10.10:5281:5281/tcp
     - 10.10.10.10:5269:5269/tcp
    environment:
     - LOCAL=stella
     - DOMAIN=event.formulastudent.de
     - PASSWORD=${PROSODY_PASSWORD}
     - DNS_SERVER=10.10.10.10
     - DNS_DOMAIN=event.formulastudent.de
    networks:
      manage:
        ipv4_address: 10.10.3.14

networks:
  manage:
    external: true
  dmz:
    external: true
