version: '2'
services:
  cups:
    build: cups
    restart: always
    ports:
     - 10.10.10.10:631:631/tcp
    volumes:
     - /data/cups/config:/var/cups_config
     - /data/cups/driver:/var/cups_driver
    environment:
     - CUPS_ADMIN=${CUPS_USER}
     - CUPS_PASSWD=${CUPS_PASSWORD}
